In [ ]:
#this script will scrape the data for every player for every game for the provided season.

In [ ]:
#this is likely the endpoint we will use:
from nba_api.stats.endpoints import leaguegamefinder
from sqlalchemy import create_engine
from requests.exceptions import ReadTimeout
import pandas as pd
import random
import time 
import json

#create our engine for pushing to sql database
from dotenv import load_dotenv
import os

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

engine = create_engine(DATABASE_URL)

#define seasons to gather data for 
seasons = ['2022-23', '2023-24', '2024-25']

for season in seasons:
    try:
        # Get all games for a season
        game_finder = leaguegamefinder.LeagueGameFinder(
            season_nullable=season,  # Format: YYYY-YY
            league_id_nullable='00',    # 00 is NBA
            season_type_nullable='Regular Season'  # or 'Playoffs'
        )
        
        # Convert to DataFrame
        games_df = game_finder.get_data_frames()[0]
        
        #make team ID the index, and sort the dataframe based on ID and gameDate
        games_df = games_df.set_index('TEAM_ID')
        games_df_sorted = games_df.sort_values(['TEAM_ID', 'GAME_DATE'], ascending=[True, False])
    
        #once we've created the dataframe, we want to push that to a SQL database
        filename = f"{season}_historic_game_data"
        games_df_sorted.to_sql(filename, engine, if_exists='replace', index=True)
        print(f"Created and stored dataframe for {season} season")
        print()
        time.sleep(round(random.uniform(3, 6), 1))

    #handle timeout/api rejection errors
    except (ReadTimeout, json.decoder.JSONDecodeError) as e:
        print(f"Error for {season}: {e} - retrying after 60 seconds")
        time.sleep(60)
        continue

print("Finished data gathering for specified seasons")

Created and stored dataframe for 2022-23 season

Created and stored dataframe for 2023-24 season

Created and stored dataframe for 2024-25 season

Finished data gathering for specified seasons

In [11]:
games_df_sorted

,SEASON_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
TEAM_ID,,,,,,,,,,,,,,,,,,,,,
1610612737,22024,ATL,Atlanta Hawks,0022400656,2025-01-27,ATL @ MIN,L,241,92,34,...,0.667,14,37,51,24,10,3,21,20,-8.0
1610612737,22024,ATL,Atlanta Hawks,0022400639,2025-01-25,ATL vs. TOR,L,238,94,33,...,0.680,8,35,43,28,14,5,22,20,-23.0
1610612737,22024,ATL,Atlanta Hawks,0022400623,2025-01-23,ATL vs. TOR,L,240,119,42,...,0.733,9,27,36,30,11,2,14,21,-3.0
1610612737,22024,ATL,Atlanta Hawks,0022400612,2025-01-22,ATL vs. DET,L,241,104,39,...,0.769,15,32,47,25,14,3,13,14,-10.0
1610612737,22024,ATL,Atlanta Hawks,0022400602,2025-01-20,ATL @ NYK,L,239,110,40,...,0.773,16,25,41,23,10,6,23,21,-9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1610612766,22024,CHA,Charlotte Hornets,0022400132,2024-11-01,CHA vs. BOS,L,241,109,42,...,0.500,12,30,42,20,5,5,14,26,-15.0
1610612766,22024,CHA,Charlotte Hornets,0022400117,2024-10-30,CHA vs. TOR,W,239,138,49,...,0.800,14,24,38,31,9,8,15,24,5.0
1610612766,22024,CHA,Charlotte Hornets,0022400088,2024-10-26,CHA vs. MIA,L,241,106,39,...,0.714,15,31,46,20,6,5,17,24,-8.0
1610612766,22024,CHA,Charlotte Hornets,0022400079,2024-10-25,CHA @ ATL,L,241,120,37,...,0.806,22,31,53,22,7,4,17,28,-5.0
1610612766,22024,CHA,Charlotte Hornets,0022400068,2024-10-23,CHA @ HOU,W,241,110,38,...,0.792,15,41,56,20,6,10,16,21,5.0

In [ ]:
#Below is the iteration we used to create the script

In [1]:
#this is likely the endpoint we will use:
from nba_api.stats.endpoints import leaguegamefinder
import pandas as pd

# Get all games for a season
game_finder = leaguegamefinder.LeagueGameFinder(
    season_nullable='2023-24',  # Format: YYYY-YY
    league_id_nullable='00',    # 00 is NBA
    season_type_nullable='Regular Season'  # or 'Playoffs'
)

# Convert to DataFrame
games_df = game_finder.get_data_frames()[0]
pd.set_option('display.max_rows', )

games_df

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22023,1610612744,GSW,Golden State Warriors,0022301198,2024-04-14,GSW vs. UTA,W,239,123,...,0.826,12,30,42,35,10,6,9,14,7.0
1,22023,1610612747,LAL,Los Angeles Lakers,0022301195,2024-04-14,LAL @ NOP,W,241,124,...,0.944,7,32,39,32,12,3,14,13,16.0
2,22023,1610612756,PHX,Phoenix Suns,0022301194,2024-04-14,PHX @ MIN,W,244,125,...,0.833,13,19,32,28,13,3,12,24,19.0
3,22023,1610612749,MIL,Milwaukee Bucks,0022301191,2024-04-14,MIL @ ORL,L,238,88,...,0.913,7,27,34,16,10,4,17,18,-25.0
4,22023,1610612754,IND,Indiana Pacers,0022301188,2024-04-14,IND vs. ATL,W,239,157,...,0.800,12,36,48,41,10,6,14,24,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,22023,1610612764,WAS,Washington Wizards,0022300064,2023-10-25,WAS @ IND,L,238,120,...,0.793,11,34,45,28,6,9,14,11,-23.0
2456,22023,1610612747,LAL,Los Angeles Lakers,0022300061,2023-10-24,LAL @ DEN,L,239,107,...,0.750,13,31,44,23,5,4,11,18,-12.0
2457,22023,1610612743,DEN,Denver Nuggets,0022300061,2023-10-24,DEN vs. LAL,W,240,119,...,0.750,9,33,42,29,9,6,11,15,12.0
2458,22023,1610612756,PHX,Phoenix Suns,0022300062,2023-10-24,PHX @ GSW,W,241,108,...,0.765,17,43,60,23,5,7,19,22,4.0
2459,22023,1610612744,GSW,Golden State Warriors,0022300062,2023-10-24,GSW vs. PHX,L,240,104,...,0.786,18,31,49,19,11,6,11,23,-4.0

In [5]:
import pandas as pd

pd.set_option('display.max_rows', 2460)
games_df

     SEASON_ID     TEAM_ID TEAM_ABBREVIATION               TEAM_NAME  \
0        22023  1610612744               GSW   Golden State Warriors
1        22023  1610612747               LAL      Los Angeles Lakers
2        22023  1610612756               PHX            Phoenix Suns
3        22023  1610612749               MIL         Milwaukee Bucks
4        22023  1610612754               IND          Indiana Pacers
5        22023  1610612741               CHI           Chicago Bulls
6        22023  1610612742               DAL        Dallas Mavericks
7        22023  1610612750               MIN  Minnesota Timberwolves
8        22023  1610612761               TOR         Toronto Raptors
9        22023  1610612758               SAC        Sacramento Kings
10       22023  1610612751               BKN           Brooklyn Nets
11       22023  1610612739               CLE     Cleveland Cavaliers
12       22023  1610612737               ATL           Atlanta Hawks
13       22023  1610612746               LAC             LA Clippers
14       22023  1610612765               DET         Detroit Pistons
15       22023  1610612748               MIA              Miami Heat
16       22023  1610612766               CHA       Charlotte Hornets
17       22023  1610612760               OKC   Oklahoma City Thunder
18       22023  1610612738               BOS          Boston Celtics
19       22023  1610612743               DEN          Denver Nuggets
20       22023  1610612752               NYK         New York Knicks
21       22023  1610612757               POR  Portland Trail Blazers
22       22023  1610612762               UTA               Utah Jazz
23       22023  1610612755               PHI      Philadelphia 76ers
24       22023  1610612764               WAS      Washington Wizards
25       22023  1610612763               MEM       Memphis Grizzlies
26       22023  1610612753               ORL           Orlando Magic
27       22023  1610612745               HOU         Houston Rockets
28       22023  1610612740               NOP    New Orleans Pelicans
29       22023  1610612759               SAS       San Antonio Spurs
30       22023  1610612758               SAC        Sacramento Kings
31       22023  1610612765               DET         Detroit Pistons
32       22023  1610612744               GSW   Golden State Warriors
33       22023  1610612742               DAL        Dallas Mavericks
34       22023  1610612749               MIL         Milwaukee Bucks
35       22023  1610612751               BKN           Brooklyn Nets
36       22023  1610612766               CHA       Charlotte Hornets
37       22023  1610612740               NOP    New Orleans Pelicans
38       22023  1610612738               BOS          Boston Celtics
39       22023  1610612739               CLE     Cleveland Cavaliers
40       22023  1610612756               PHX            Phoenix Suns
41       22023  1610612755               PHI      Philadelphia 76ers
42       22023  1610612745               HOU         Houston Rockets
43       22023  1610612746               LAC             LA Clippers
44       22023  1610612741               CHI           Chicago Bulls
45       22023  1610612737               ATL           Atlanta Hawks
46       22023  1610612747               LAL      Los Angeles Lakers
47       22023  1610612761               TOR         Toronto Raptors
48       22023  1610612757               POR  Portland Trail Blazers
49       22023  1610612764               WAS      Washington Wizards
50       22023  1610612760               OKC   Oklahoma City Thunder
51       22023  1610612752               NYK         New York Knicks
52       22023  1610612753               ORL           Orlando Magic
53       22023  1610612748               MIA              Miami Heat
54       22023  1610612754               IND          Indiana Pacers
55       22023  1610612763               MEM       Memphis Grizzlies
56       22023  1610612759               SAS       San Antonio Spurs
57       22023  1610612743               DEN          Denver Nuggets
58       22023  1610612750               MIN  Minnesota Timberwolves
59       22023  1610612762               UTA               Utah Jazz
60       22023  1610612738               BOS          Boston Celtics
61       22023  1610612758               SAC        Sacramento Kings
62       22023  1610612752               NYK         New York Knicks
63       22023  1610612741               CHI           Chicago Bulls
64       22023  1610612745               HOU         Houston Rockets
65       22023  1610612757               POR  Portland Trail Blazers
66       22023  1610612765               DET         Detroit Pistons
67       22023  1610612744               GSW   Golden State Warriors
68       22023  1610612740               NOP    New Orleans Pelicans
69       22023  1610612762               UTA               Utah Jazz
70       22023  1610612759               SAS       San Antonio Spurs
71       22023  1610612749               MIL         Milwaukee Bucks
72       22023  1610612737               ATL           Atlanta Hawks
73       22023  1610612766               CHA       Charlotte Hornets
74       22023  1610612750               MIN  Minnesota Timberwolves
75       22023  1610612746               LAC             LA Clippers
76       22023  1610612748               MIA              Miami Heat
77       22023  1610612761               TOR         Toronto Raptors
78       22023  1610612742               DAL        Dallas Mavericks
79       22023  1610612751               BKN           Brooklyn Nets
80       22023  1610612743               DEN          Denver Nuggets
81       22023  1610612763               MEM       Memphis Grizzlies
82       22023  1610612739               CLE     Cleveland Cavaliers
83       22023  1610612753               ORL           Orlando Magic
84       22023  1610612756               PHX            Phoenix Suns
85       22023  1610612760               OKC   Oklahoma City Thunder
86       22023  1610612753               ORL           Orlando Magic
87       22023  1610612745               HOU         Houston Rockets
88       22023  1610612742               DAL        Dallas Mavericks
89       22023  1610612749               MIL         Milwaukee Bucks
90       22023  1610612759               SAS       San Antonio Spurs
91       22023  1610612758               SAC        Sacramento Kings
92       22023  1610612760               OKC   Oklahoma City Thunder
93       22023  1610612762               UTA               Utah Jazz
94       22023  1610612737               ATL           Atlanta Hawks
95       22023  1610612761               TOR         Toronto Raptors
96       22023  1610612766               CHA       Charlotte Hornets
97       22023  1610612756               PHX            Phoenix Suns
98       22023  1610612752               NYK         New York Knicks
99       22023  1610612738               BOS          Boston Celtics
100      22023  1610612746               LAC             LA Clippers
101      22023  1610612765               DET         Detroit Pistons
102      22023  1610612754               IND          Indiana Pacers
103      22023  1610612741               CHI           Chicago Bulls
104      22023  1610612740               NOP    New Orleans Pelicans
105      22023  1610612748               MIA              Miami Heat
106      22023  1610612757               POR  Portland Trail Blazers
107      22023  1610612750               MIN  Minnesota Timberwolves
108      22023  1610612743               DEN          Denver Nuggets
109      22023  1610612763               MEM       Memphis Grizzlies
110      22023  1610612755               PHI      Philadelphia 76ers
111      22023  1610612764               WAS      Washington Wizards
112      22023  1610612744               GSW   Golden State Warriors
113      22023  1610612747               LAL      Los Angeles Lakers
114      22023  1610612741               CHI           Chicago Bulls
115      22023  1610612749               MIL         Milwaukee Bucks
116      22023  1610612752               NYK         New York Knicks
117      22023  1610612751               BKN           Brooklyn Nets
118      22023  1610612738               BOS          Boston Celtics
119      22023  1610612745               HOU         Houston Rockets
120      22023  1610612755               PHI      Philadelphia 76ers
121      22023  1610612757               POR  Portland Trail Blazers
122      22023  1610612750               MIN  Minnesota Timberwolves
123      22023  1610612766               CHA       Charlotte Hornets
124      22023  1610612742               DAL        Dallas Mavericks
125      22023  1610612753               ORL           Orlando Magic
126      22023  1610612754               IND          Indiana Pacers
127      22023  1610612758               SAC        Sacramento Kings
128      22023  1610612759               SAS       San Antonio Spurs
129      22023  1610612748               MIA              Miami Heat
130      22023  1610612739               CLE     Cleveland Cavaliers
131      22023  1610612761               TOR         Toronto Raptors
132      22023  1610612747               LAL      Los Angeles Lakers
133      22023  1610612762               UTA               Utah Jazz
134      22023  1610612744               GSW   Golden State Warriors
135      22023  1610612764               WAS      Washington Wizards
136      22023  1610612746               LAC             LA Clippers
137      22023  1610612740               NOP    New Orleans Pelicans
138      22023  1610612760               OKC   Oklahoma City Thunder
139      22023  1610612756               PHX            Phoenix Suns
140      22023  1610612743               DEN          Denver Nuggets
141      22023  1610612739               CLE     Cleveland Cavaliers
142      22023  1610612737               ATL           Atlanta Hawks
143      22023  1610612751               BKN           Brooklyn Nets
144      22023  1610612755               PHI      Philadelphia 76ers
145      22023  1610612765               DET         Detroit Pistons
146      22023  1610612747               LAL      Los Angeles Lakers
147      22023  1610612763               MEM       Memphis Grizzlies
148      22023  1610612757               POR  Portland Trail Blazers
149      22023  1610612749               MIL         Milwaukee Bucks
150      22023  1610612764               WAS      Washington Wizards
151      22023  1610612762               UTA               Utah Jazz
152      22023  1610612746               LAC             LA Clippers
153      22023  1610612744               GSW   Golden State Warriors
154      22023  1610612756               PHX            Phoenix Suns
155      22023  1610612753               ORL           Orlando Magic
156      22023  1610612754               IND          Indiana Pacers
157      22023  1610612752               NYK         New York Knicks
158      22023  1610612748               MIA              Miami Heat
159      22023  1610612765               DET         Detroit Pistons
160      22023  1610612760               OKC   Oklahoma City Thunder
161      22023  1610612763               MEM       Memphis Grizzlies
162      22023  1610612741               CHI           Chicago Bulls
163      22023  1610612758               SAC        Sacramento Kings
164      22023  1610612761               TOR         Toronto Raptors
165      22023  1610612742               DAL        Dallas Mavericks
166      22023  1610612750               MIN  Minnesota Timberwolves
167      22023  1610612766               CHA       Charlotte Hornets
168      22023  1610612759               SAS       San Antonio Spurs
169      22023  1610612745               HOU         Houston Rockets
170      22023  1610612738               BOS          Boston Celtics
171      22023  1610612740               NOP    New Orleans Pelicans
172      22023  1610612737               ATL           Atlanta Hawks
173      22023  1610612744               GSW   Golden State Warriors
174      22023  1610612752               NYK         New York Knicks
175      22023  1610612758               SAC        Sacramento Kings
176      22023  1610612746               LAC             LA Clippers
177      22023  1610612745               HOU         Houston Rockets
178      22023  1610612748               MIA              Miami Heat
179      22023  1610612755               PHI      Philadelphia 76ers
180      22023  1610612743               DEN          Denver Nuggets
181      22023  1610612742               DAL        Dallas Mavericks
182      22023  1610612761               TOR         Toronto Raptors
183      22023  1610612754               IND          Indiana Pacers
184      22023  1610612753               ORL           Orlando Magic
185      22023  1610612750               MIN  Minnesota Timberwolves
186      22023  1610612765               DET         Detroit Pistons
187      22023  1610612766               CHA       Charlotte Hornets
188      22023  1610612739               CLE     Cleveland Cavaliers
189      22023  1610612747               LAL      Los Angeles Lakers
190      22023  1610612737               ATL           Atlanta Hawks
191      22023  1610612756               PHX            Phoenix Suns
192      22023  1610612763               MEM       Memphis Grizzlies
193      22023  1610612760               OKC   Oklahoma City Thunder
194      22023  1610612740               NOP    New Orleans Pelicans
195      22023  1610612751               BKN           Brooklyn Nets
196      22023  1610612749               MIL         Milwaukee Bucks
197      22023  1610612757               POR  Portland Trail Blazers
198      22023  1610612738               BOS          Boston Celtics
199      22023  1610612764               WAS      Washington Wizards
200      22023  1610612742               DAL        Dallas Mavericks
201      22023  1610612758               SAC        Sacramento Kings
202      22023  1610612759               SAS       San Antonio Spurs
203      22023  1610612747               LAL      Los Angeles Lakers
204      22023  1610612739               CLE     Cleveland Cavaliers
205      22023  1610612755               PHI      Philadelphia 76ers
206      22023  1610612749               MIL         Milwaukee Bucks
207      22023  1610612762               UTA               Utah Jazz
208      22023  1610612743               DEN          Denver Nuggets
209      22023  1610612744               GSW   Golden State Warriors
210      22023  1610612760               OKC   Oklahoma City Thunder
211      22023  1610612761               TOR         Toronto Raptors
212      22023  1610612748               MIA              Miami Heat
213      22023  1610612750               MIN  Minnesota Timberwolves
214      22023  1610612745               HOU         Houston Rockets
215      22023  1610612746               LAC             LA Clippers
216      22023  1610612764               WAS      Washington Wizards
217      22023  1610612752               NYK         New York Knicks
218      22023  1610612754               IND          Indiana Pacers
219      22023  1610612756               PHX            Phoenix Suns
220      22023  1610612765               DET         Detroit Pistons
221      22023  1610612738               BOS          Boston Celtics
222      22023  1610612763               MEM       Memphis Grizzlies
223      22023  1610612741               CHI           Chicago Bulls
224      22023  1610612766               CHA       Charlotte Hornets
225      22023  1610612757               POR  Portland Trail Blazers
226      22023  1610612753               ORL           Orlando Magic
227      22023  1610612740               NOP    New Orleans Pelicans
228      22023  1610612751               BKN           Brooklyn Nets
229      22023  1610612737               ATL           Atlanta Hawks
230      22023  1610612762               UTA               Utah Jazz
231      22023  1610612764               WAS      Washington Wizards
232      22023  1610612759               SAS       San Antonio Spurs
233      22023  1610612751               BKN           Brooklyn Nets
234      22023  1610612758               SAC        Sacramento Kings
235      22023  1610612760               OKC   Oklahoma City Thunder
236      22023  1610612741               CHI           Chicago Bulls
237      22023  1610612761               TOR         Toronto Raptors
238      22023  1610612739               CLE     Cleveland Cavaliers
239      22023  1610612748               MIA              Miami Heat
240      22023  1610612747               LAL      Los Angeles Lakers
241      22023  1610612744               GSW   Golden State Warriors
242      22023  1610612750               MIN  Minnesota Timberwolves
243      22023  1610612755               PHI      Philadelphia 76ers
244      22023  1610612766               CHA       Charlotte Hornets
245      22023  1610612742               DAL        Dallas Mavericks
246      22023  1610612746               LAC             LA Clippers
247      22023  1610612743               DEN          Denver Nuggets
248      22023  1610612752               NYK         New York Knicks
249      22023  1610612745               HOU         Houston Rockets
250      22023  1610612740               NOP    New Orleans Pelicans
251      22023  1610612753               ORL           Orlando Magic
252      22023  1610612737               ATL           Atlanta Hawks
253      22023  1610612738               BOS          Boston Celtics
254      22023  1610612749               MIL         Milwaukee Bucks
255      22023  1610612763               MEM       Memphis Grizzlies
256      22023  1610612748               MIA              Miami Heat
257      22023  1610612765               DET         Detroit Pistons
258      22023  1610612750               MIN  Minnesota Timberwolves
259      22023  1610612764               WAS      Washington Wizards
260      22023  1610612739               CLE     Cleveland Cavaliers
261      22023  1610612757               POR  Portland Trail Blazers
262      22023  1610612751               BKN           Brooklyn Nets
263      22023  1610612747               LAL      Los Angeles Lakers
264      22023  1610612754               IND          Indiana Pacers
265      22023  1610612760               OKC   Oklahoma City Thunder
266      22023  1610612743               DEN          Denver Nuggets
267      22023  1610612745               HOU         Houston Rockets
268      22023  1610612766               CHA       Charlotte Hornets
269      22023  1610612744               GSW   Golden State Warriors
270      22023  1610612762               UTA               Utah Jazz
271      22023  1610612753               ORL           Orlando Magic
272      22023  1610612758               SAC        Sacramento Kings
273      22023  1610612742               DAL        Dallas Mavericks
274      22023  1610612752               NYK         New York Knicks
275      22023  1610612756               PHX            Phoenix Suns
276      22023  1610612759               SAS       San Antonio Spurs
277      22023  1610612746               LAC             LA Clippers
278      22023  1610612741               CHI           Chicago Bulls
279      22023  1610612755               PHI      Philadelphia 76ers
280      22023  1610612738               BOS          Boston Celtics
281      22023  1610612749               MIL         Milwaukee Bucks
282      22023  1610612740               NOP    New Orleans Pelicans
283      22023  1610612737               ATL           Atlanta Hawks
284      22023  1610612746               LAC             LA Clippers
285      22023  1610612744               GSW   Golden State Warriors
286      22023  1610612764               WAS      Washington Wizards
287      22023  1610612766               CHA       Charlotte Hornets

In [15]:
games_df = games_df.set_index('TEAM_ID')

KeyError: "None of ['TEAM_ID'] are in the columns"

In [24]:
games_df.loc[1610612744]

,SEASON_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
TEAM_ID,,,,,,,,,,,,,,,,,,,,,
1610612744,22023,GSW,Golden State Warriors,0022301198,2024-04-14,GSW vs. UTA,W,239,123,45,...,0.826,12,30,42,35,10,6,9,14,7.0
1610612744,22023,GSW,Golden State Warriors,0022301182,2024-04-12,GSW vs. NOP,L,240,109,40,...,0.762,11,42,53,27,6,5,16,15,-5.0
1610612744,22023,GSW,Golden State Warriors,0022301169,2024-04-11,GSW @ POR,W,240,100,36,...,0.800,10,36,46,24,8,13,16,18,8.0
1610612744,22023,GSW,Golden State Warriors,0022301155,2024-04-09,GSW @ LAL,W,241,134,47,...,0.667,4,38,42,37,3,12,15,17,14.0
1610612744,22023,GSW,Golden State Warriors,0022301142,2024-04-07,GSW vs. UTA,W,241,118,49,...,1.000,11,36,47,32,9,8,13,19,8.0
1610612744,22023,GSW,Golden State Warriors,0022301097,2024-04-05,GSW @ DAL,L,239,106,41,...,0.667,11,33,44,27,12,5,15,19,-2.0
1610612744,22023,GSW,Golden State Warriors,0022301113,2024-04-04,GSW @ HOU,W,241,133,47,...,0.880,12,31,43,29,6,2,18,23,23.0
1610612744,22023,GSW,Golden State Warriors,0022300589,2024-04-02,GSW vs. DAL,W,242,104,41,...,1.000,11,41,52,29,9,4,17,18,4.0
1610612744,22023,GSW,Golden State Warriors,0022301085,2024-03-31,GSW @ SAS,W,241,117,45,...,0.846,12,29,41,34,15,3,15,14,4.0
1610612744,22023,GSW,Golden State Warriors,0022301062,2024-03-29,GSW @ CHA,W,240,115,48,...,0.889,11,39,50,35,7,5,12,19,18.0
1610612744,22023,GSW,Golden State Warriors,0022301049,2024-03-27,GSW @ ORL,W,241,101,40,...,0.846,12,40,52,26,5,5,12,18,8.0
1610612744,22023,GSW,Golden State Warriors,0022301044,2024-03-26,GSW @ MIA,W,243,113,47,...,0.600,7,36,43,31,6,5,10,20,21.0
1610612744,22023,GSW,Golden State Warriors,0022301031,2024-03-24,GSW @ MIN,L,241,110,38,...,0.769,7,34,41,23,8,3,12,19,-4.0
1610612744,22023,GSW,Golden State Warriors,0022301016,2024-03-22,GSW vs. IND,L,240,111,43,...,0.688,24,40,64,24,6,6,14,15,-12.0
1610612744,22023,GSW,Golden State Warriors,0022301001,2024-03-20,GSW vs. MEM,W,240,137,58,...,0.333,13,35,48,43,6,5,6,17,21.0
1610612744,22023,GSW,Golden State Warriors,0022300988,2024-03-18,GSW vs. NYK,L,241,112,42,...,0.778,12,27,39,29,7,5,13,16,-7.0
1610612744,22023,GSW,Golden State Warriors,0022300973,2024-03-16,GSW @ LAL,W,241,128,51,...,0.800,14,31,45,38,3,4,7,19,7.0
1610612744,22023,GSW,Golden State Warriors,0022300952,2024-03-13,GSW @ DAL,L,241,99,37,...,0.842,15,27,42,19,9,3,15,20,-10.0
1610612744,22023,GSW,Golden State Warriors,0022300936,2024-03-11,GSW @ SAS,W,240,112,46,...,0.667,10,35,45,28,7,4,13,19,10.0
1610612744,22023,GSW,Golden State Warriors,0022300921,2024-03-09,GSW vs. SAS,L,241,113,41,...,0.724,9,30,39,26,9,7,12,24,-13.0
1610612744,22023,GSW,Golden State Warriors,0022300907,2024-03-07,GSW vs. CHI,L,241,122,44,...,0.821,13,35,48,31,8,2,11,22,-3.0
1610612744,22023,GSW,Golden State Warriors,0022300899,2024-03-06,GSW vs. MIL,W,240,125,51,...,0.571,8,42,50,37,10,13,14,13,35.0
1610612744,22023,GSW,Golden State Warriors,0022300872,2024-03-03,GSW @ BOS,L,240,88,36,...,0.692,12,34,46,24,2,3,17,13,-52.0
1610612744,22023,GSW,Golden State Warriors,0022300860,2024-03-01,GSW @ TOR,W,241,120,44,...,0.778,15,41,56,26,10,5,14,14,15.0
1610612744,22023,GSW,Golden State Warriors,0022300852,2024-02-29,GSW @ NYK,W,242,110,44,...,0.500,16,37,53,26,8,5,11,19,11.0
1610612744,22023,GSW,Golden State Warriors,0022300834,2024-02-27,GSW @ WAS,W,240,123,47,...,0.727,9,35,44,39,12,6,18,11,11.0
1610612744,22023,GSW,Golden State Warriors,0022300824,2024-02-25,GSW vs. DEN,L,241,103,35,...,0.759,11,31,42,27,5,3,17,18,-16.0
1610612744,22023,GSW,Golden State Warriors,0022300811,2024-02-23,GSW vs. CHA,W,238,97,38,...,0.800,13,40,53,28,7,7,21,15,13.0
1610612744,22023,GSW,Golden State Warriors,0022300802,2024-02-22,GSW vs. LAL,W,241,128,50,...,0.857,15,33,48,32,6,4,9,19,18.0
1610612744,22023,GSW,Golden State Warriors,0022300576,2024-02-15,GSW @ UTA,W,239,140,49,...,0.786,13,28,41,42,8,6,13,19,3.0
1610612744,22023,GSW,Golden State Warriors,0022300789,2024-02-14,GSW vs. LAC,L,240,125,47,...,0.722,13,34,47,34,7,2,9,25,-5.0
1610612744,22023,GSW,Golden State Warriors,0022300769,2024-02-12,GSW @ UTA,W,239,129,48,...,0.765,12,39,51,31,8,4,13,13,22.0
1610612744,22023,GSW,Golden State Warriors,0022300757,2024-02-10,GSW vs. PHX,W,238,113,45,...,0.545,13,39,52,33,6,2,13,20,1.0
1610612744,22023,GSW,Golden State Warriors,0022300733,2024-02-08,GSW @ IND,W,241,131,52,...,0.769,10,39,49,33,7,7,17,22,22.0
1610612744,22023,GSW,Golden State Warriors,0022300727,2024-02-07,GSW @ PHI,W,239,127,47,...,0.773,12,40,52,30,7,8,12,21,23.0
1610612744,22023,GSW,Golden State Warriors,0022300717,2024-02-05,GSW @ BKN,W,239,109,43,...,0.826,16,44,60,24,7,8,13,17,11.0
1610612744,22023,GSW,Golden State Warriors,0022300699,2024-02-03,GSW @ ATL,L,266,134,50,...,0.800,14,43,57,26,4,7,14,23,-7.0
1610612744,22023,GSW,Golden State Warriors,0022300693,2024-02-02,GSW @ MEM,W,240,121,46,...,0.818,6,40,46,32,7,8,14,17,20.0
1610612744,22023,GSW,Golden State Warriors,0022300673,2024-01-30,GSW vs. PHI,W,239,119,44,...,0.895,8,34,42,32,6,6,16,20,12.0
1610612744,22023,GSW,Golden State Warriors,0022300650,2024-01-27,GSW vs. LAL,L,289,144,55,...,0.688,11,39,50,37,11,3,17,34,-1.0
1610612744,22023,GSW,Golden State Warriors,0022300632,2024-01-25,GSW vs. SAC,L,239,133,48,...,0.783,6,27,33,30,7,3,13,19,-1.0
1610612744,22023,GSW,Golden State Warriors,0022300626,2024-01-24,GSW vs. ATL,W,240,134,51,...,0.727,11,38,49,26,6,9,10,18,22.0
1610612744,22023,GSW,Golden State Warriors,0022300560,2024-01-15,GSW @ MEM,L,241,107,44,...,0.900,7,38,45,28,4,6,19,25,-9.0
1610612744,22023,GSW,Golden State Warriors,0022300545,2024-01-13,GSW @ MIL,L,240,118,47,...,0.643,12,29,41,23,5,4,7,16,-11.0
1610612744,22023,GSW,Golden State Warriors,0022300536,2024-01-12,GSW @ CHI,W,240,140,49,...,0.733,13,31,44,39,7,4,3,16,9.0
1610612744,22023,GSW,Golden State Warriors,0022300525,2024-01-10,GSW vs. NOP,L,239,105,39,...,0.833,14,29,43,24,4,4,17,19,-36.0
1610612744,22023,GSW,Golden State Warriors,0022300504,2024-01-07,GSW vs. TOR,L,241,118,45,...,0.933,15,28,43,30,5,4,10,11,-15.0
1610612744,22023,GSW,Golden State Warriors,0022300490,2024-01-05,GSW vs. DET,W,242,113,38,...,0.840,7,38,45,24,3,5,16,18,4.0
1610612744,22023,GSW,Golden State Warriors,0022300478,2024-01-04,GSW vs. DEN,L,240,127,49,...,0.875,9,24,33,35,4,3,8,20,-3.0
1610612744,22023,GSW,Golden State Warriors,0022300463,2024-01-02,GSW vs. ORL,W,239,121,42,...,0.649,9,27,36,23,9,6,12,19,6.0
1610612744,22023,GSW,Golden State Warriors,0022300444,2023-12-30,GSW vs. DAL,L,240,122,47,...,0.692,16,31,47,32,8,3,10,21,-10.0
1610612744,22023,GSW,Golden State Warriors,0022300426,2023-12-28,GSW vs. MIA,L,241,102,37,...,0.800,12,31,43,27,4,7,13,19,-12.0
1610612744,22023,GSW,Golden State Warriors,0022300402,2023-12-25,GSW @ DEN,L,240,114,40,...,0.870,9,30,39,23,7,3,13,23,-6.0
1610612744,22023,GSW,Golden State Warriors,0022300399,2023-12-23,GSW vs. POR,W,241,126,48,...,0.833,13,36,49,38,8,2,16,14,20.0
1610612744,22023,GSW,Golden State Warriors,0022300386,2023-12-22,GSW vs. WAS,W,240,129,47,...,0.850,14,43,57,33,5,2,12,17,11.0
1610612744,22023,GSW,Golden State Warriors,0022300362,2023-12-19,GSW vs. BOS,W,266,132,50,...,0.857,18,41,59,29,4,5,10,15,6.0
1610612744,22023,GSW,Golden State Warriors,0022300348,2023-12-17,GSW @ POR,W,240,118,46,...,0.684,11,32,43,31,10,4,14,20,4.0
1610612744,22023,GSW,Golden State Warriors,0022300339,2023-12-16,GSW vs. BKN,W,241,124,44,...,0.950,13,29,42,29,7,5,14,15,4.0
1610612744,22023,GSW,Golden State Warriors,0022300325,2023-12-14,GSW @ LAC,L,241,113,40,...,0.895,16,27,43,22,8,2,11,24,-8.0
1610612744,22023,GSW,Golden State Warriors,0022300308,2023-12-12,GSW @ PHX,L,241,116,41,...,0.667,13,38,51,26,9,1,15,28,-3.0
1610612744,22023,GSW,Golden State Warriors,0022301222,2023-12-08,GSW @ OKC,L,266,136,49,...,0.826,24,36,60,29,3,2,28,28,-2.0
1610612744,22023,GSW,Golden State Warriors,0022301214,2023-12-06,GSW vs. POR,W,239,110,36,...,0.848,15,35,50,20,4,3,17,19,4.0
1610612744,22023,GSW,Golden State Warriors,0022300280,2023-12-02,GSW @ LAC,L,241,112,38,...,0.792,6,36,42,31,5,4,13,15,-1.0
1610612744,22023,GSW,Golden State Warriors,0022300273,2023-11-30,GSW vs. LAC,W,240,120,41,...,0.742,10,37,47,30,3,4,7,18,6.0
1610612744,22023,GSW,Golden State Warriors,0022300060,2023-11-28,GSW @ SAC,L,241,123,40,...,0.867,9,43,52,25,6,6,18,31,-1.0
1610612744,22023,GSW,Golden State Warriors,0022300051,2023-11-24,GSW vs. SAS,W,241,118,40,...,0.792,7,34,41,35,7,2,24,21,6.0
1610612744,22023,GSW,Golden State Warriors,0022300236,2023-11-22,GSW @ PHX,L,240,115,43,...,0.655,11,32,43,29,10,3,15,34,-8.0
1610612744,22023,GSW,Golden State Warriors,0022300224,2023-11-20,GSW vs. HOU,W,240,121,36,...,0.848,8,35,43,26,3,1,8,21,5.0
1610612744,22023,GSW,Golden State Warriors,0022300207,2023-11-18,GSW vs. OKC,L,266,123,44,...,0.810,14,35,49,33,6,4,16,18,-7.0
1610612744,22023,GSW,Golden State Warriors,0022300201,2023-11-16,GSW vs. OKC,L,240,109,40,...,0.789,20,29,49,27,5,4,16,19,-19.0
1610612744,22023,GSW,Golden State Warriors,0022300025,2023-11-14,GSW vs. MIN,L,242,101,37,...,0.875,13,33,46,28,11,2,19,22,-3.0
1610612744,22023,GSW,Golden State Warriors,0022300186,2023-11-12,GSW vs. MIN,L,239,110,37,...,0.857,19,32,51,24,9,0,14,28,-6.0
1610612744,22023,GSW,Golden State Warriors,0022300176,2023-11-11,GSW vs. CLE,L,240,110,37,...,0.767,15,40,55,26,5,3,20,29,-8.0
1610612744,22023,GSW,Golden State Warriors,0022300169,2023-11-08,GSW @ DEN,L,240,105,37,...,0.769,11,38,49,21,5,0,9,20,-3.0
1610612744,22023,GSW,Golden State Warriors,0022300145,2023-11-06,GSW @ DET,W,240,120,46,...,0.762,17,27,44,26,8,4,11,14,11.0
1610612744,22023,GSW,Golden State Warriors,0022300142,2023-11-05,GSW @ CLE,L,240,104,34,...,0.667,17,27,44,26,10,4,13,18,-11.0
1610612744,22023,GSW,Golden State Warriors,0022300005,2023-11-03,GSW @ OKC,W,241,141,49,...,0.833,13,25,38,36,9,2,15,25,2.0
1610612744,22023,GSW,Golden State Warriors,0022300126,2023-11-01,GSW vs. SAC,W,239,102,39,...,0.867,7,29,36,32,5,6,17,17,1.0
1610612744,22023,GSW,Golden State Warriors,0022300108,2023-10-30,GSW @ NOP,W,242,130,51,...,0.650,21,43,64,28,6,7,14,21,28.0
1610612744,22023,GSW,Golden State Warriors,0022300096,2023-10-29,GSW @ HOU,W,239,106,35,...,0.783,8,41,49,27,6,6,14,18,11.0
1610612744,22023,GSW,Golden State Warriors,0022300087,2023-10-27,GSW @ SAC,W,240,122,48,...,0.857,7,32,39,32,14,3,19,24,8.0
1610612744,22023,GSW,Golden State Warriors,0022300062,2023-10-24,GSW vs. PHX,L,240,104,36,...,0.786,18,31,49,19,11,6,11,23,-4.0

In [36]:
games_df_sorted = games_df.sort_values(['TEAM_ID', 'GAME_DATE'], ascending=[True, False])

In [38]:
games_df_sorted

,SEASON_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
TEAM_ID,,,,,,,,,,,,,,,,,,,,,
1610612737,22023,ATL,Atlanta Hawks,0022301188,2024-04-14,ATL @ IND,L,241,115,39,...,0.926,9,23,32,25,6,5,15,12,-42.0
1610612737,22023,ATL,Atlanta Hawks,0022301178,2024-04-12,ATL @ MIN,L,240,106,40,...,0.680,9,31,40,23,4,1,14,25,-3.0
1610612737,22023,ATL,Atlanta Hawks,0022301159,2024-04-10,ATL vs. CHA,L,240,114,43,...,0.625,7,31,38,35,7,2,16,20,-1.0
1610612737,22023,ATL,Atlanta Hawks,0022301147,2024-04-09,ATL vs. MIA,L,292,111,45,...,0.786,17,42,59,28,13,2,15,23,-6.0
1610612737,22023,ATL,Atlanta Hawks,0022301130,2024-04-06,ATL @ DEN,L,240,110,37,...,0.828,11,27,38,30,8,2,16,18,-32.0
1610612737,22023,ATL,Atlanta Hawks,0022301124,2024-04-04,ATL @ DAL,L,239,95,34,...,0.667,11,45,56,21,7,2,21,22,-14.0
1610612737,22023,ATL,Atlanta Hawks,0022301104,2024-04-03,ATL vs. DET,W,240,121,49,...,0.667,6,42,48,36,9,8,16,13,8.0
1610612737,22023,ATL,Atlanta Hawks,0022301091,2024-04-01,ATL @ CHI,W,240,113,41,...,0.667,8,37,45,29,4,5,14,21,12.0
1610612737,22023,ATL,Atlanta Hawks,0022301076,2024-03-30,ATL vs. MIL,L,239,113,42,...,0.833,9,30,39,24,5,3,11,26,-9.0
1610612737,22023,ATL,Atlanta Hawks,0022301060,2024-03-28,ATL vs. BOS,W,265,123,51,...,0.600,17,36,53,24,5,5,11,17,1.0
1610612737,22023,ATL,Atlanta Hawks,0022301051,2024-03-27,ATL vs. POR,W,240,120,44,...,0.800,8,33,41,23,12,9,16,17,14.0
1610612737,22023,ATL,Atlanta Hawks,0022301034,2024-03-25,ATL vs. BOS,W,241,120,46,...,0.588,15,29,44,30,5,3,13,18,2.0
1610612737,22023,ATL,Atlanta Hawks,0022301021,2024-03-23,ATL vs. CHA,W,240,132,50,...,0.857,11,32,43,40,9,5,8,14,41.0
1610612737,22023,ATL,Atlanta Hawks,0022301010,2024-03-21,ATL @ PHX,L,241,115,40,...,0.793,12,24,36,27,11,3,8,23,-13.0
1610612737,22023,ATL,Atlanta Hawks,0022300990,2024-03-18,ATL @ LAL,L,240,105,42,...,0.800,12,30,42,32,8,5,9,14,-31.0
1610612737,22023,ATL,Atlanta Hawks,0022300982,2024-03-17,ATL @ LAC,W,240,110,41,...,0.917,10,35,45,32,10,7,14,22,17.0
1610612737,22023,ATL,Atlanta Hawks,0022300966,2024-03-15,ATL @ UTA,L,241,122,41,...,0.741,11,30,41,32,7,5,9,16,-2.0
1610612737,22023,ATL,Atlanta Hawks,0022300953,2024-03-13,ATL @ POR,L,240,102,38,...,0.667,13,25,38,19,11,6,14,23,-4.0
1610612737,22023,ATL,Atlanta Hawks,0022300925,2024-03-10,ATL vs. NOP,L,240,103,38,...,0.769,12,29,41,28,6,4,11,15,-13.0
1610612737,22023,ATL,Atlanta Hawks,0022300913,2024-03-08,ATL @ MEM,W,240,99,37,...,0.667,15,32,47,21,9,5,14,20,7.0
1610612737,22023,ATL,Atlanta Hawks,0022300895,2024-03-06,ATL vs. CLE,W,241,112,43,...,0.750,8,34,42,27,7,3,9,17,11.0
1610612737,22023,ATL,Atlanta Hawks,0022300889,2024-03-05,ATL @ NYK,W,239,116,44,...,0.783,13,38,51,26,6,5,14,13,16.0
1610612737,22023,ATL,Atlanta Hawks,0022300866,2024-03-02,ATL @ BKN,L,241,102,37,...,0.739,12,30,42,23,4,4,11,19,-12.0
1610612737,22023,ATL,Atlanta Hawks,0022300851,2024-02-29,ATL @ BKN,L,241,97,37,...,0.714,8,31,39,18,3,8,11,14,-27.0
1610612737,22023,ATL,Atlanta Hawks,0022300835,2024-02-27,ATL vs. UTA,W,239,124,46,...,0.870,15,40,55,27,8,8,17,15,27.0
1610612737,22023,ATL,Atlanta Hawks,0022300821,2024-02-25,ATL vs. ORL,W,241,109,41,...,0.882,9,35,44,31,10,3,9,17,17.0
1610612737,22023,ATL,Atlanta Hawks,0022300804,2024-02-23,ATL vs. TOR,L,239,121,46,...,0.708,20,34,54,27,5,4,9,11,-2.0
1610612737,22023,ATL,Atlanta Hawks,0022300777,2024-02-14,ATL @ CHA,L,239,99,36,...,0.900,15,30,45,23,5,6,16,20,-23.0
1610612737,22023,ATL,Atlanta Hawks,0022300763,2024-02-12,ATL vs. CHI,L,241,126,44,...,0.828,15,34,49,33,4,3,11,20,-10.0
1610612737,22023,ATL,Atlanta Hawks,0022300754,2024-02-10,ATL vs. HOU,W,240,122,40,...,0.757,9,32,41,25,7,8,11,18,9.0
1610612737,22023,ATL,Atlanta Hawks,0022300742,2024-02-09,ATL @ PHI,W,240,127,42,...,0.818,9,31,40,31,4,9,13,19,6.0
1610612737,22023,ATL,Atlanta Hawks,0022300729,2024-02-07,ATL @ BOS,L,240,117,43,...,0.900,13,36,49,24,8,2,9,13,-8.0
1610612737,22023,ATL,Atlanta Hawks,0022300716,2024-02-05,ATL vs. LAC,L,240,144,51,...,0.815,13,26,39,35,5,4,11,22,-5.0
1610612737,22023,ATL,Atlanta Hawks,0022300699,2024-02-03,ATL vs. GSW,W,264,141,55,...,0.773,16,41,57,27,5,4,8,20,7.0
1610612737,22023,ATL,Atlanta Hawks,0022300690,2024-02-02,ATL vs. PHX,W,240,129,49,...,0.778,12,31,43,29,7,4,9,13,9.0
1610612737,22023,ATL,Atlanta Hawks,0022300669,2024-01-30,ATL vs. LAL,W,240,138,53,...,0.889,12,34,46,32,10,2,12,18,16.0
1610612737,22023,ATL,Atlanta Hawks,0022300653,2024-01-28,ATL vs. TOR,W,241,126,44,...,0.800,20,31,51,27,7,4,14,21,1.0
1610612737,22023,ATL,Atlanta Hawks,0022300634,2024-01-26,ATL vs. DAL,L,239,143,51,...,0.867,12,24,36,32,7,2,7,24,-5.0
1610612737,22023,ATL,Atlanta Hawks,0022300626,2024-01-24,ATL @ GSW,L,241,112,39,...,0.769,13,32,45,30,7,2,10,16,-22.0
1610612737,22023,ATL,Atlanta Hawks,0022300613,2024-01-22,ATL @ SAC,L,240,107,36,...,0.778,13,37,50,19,2,7,12,19,-15.0
1610612737,22023,ATL,Atlanta Hawks,0022300595,2024-01-20,ATL vs. CLE,L,239,95,37,...,0.667,11,34,45,25,5,4,11,15,-21.0
1610612737,22023,ATL,Atlanta Hawks,0022300587,2024-01-19,ATL @ MIA,W,241,109,40,...,0.824,9,29,38,23,6,2,13,20,1.0
1610612737,22023,ATL,Atlanta Hawks,0022300570,2024-01-17,ATL vs. ORL,W,239,106,39,...,0.909,10,31,41,21,8,2,23,17,2.0
1610612737,22023,ATL,Atlanta Hawks,0022300559,2024-01-15,ATL vs. SAS,W,241,109,40,...,0.762,13,44,57,24,8,6,16,19,10.0
1610612737,22023,ATL,Atlanta Hawks,0022300543,2024-01-13,ATL vs. WAS,L,240,99,32,...,0.727,16,34,50,21,9,7,14,20,-28.0
1610612737,22023,ATL,Atlanta Hawks,0022300533,2024-01-12,ATL vs. IND,L,242,108,40,...,0.739,12,16,28,25,14,2,14,13,-18.0
1610612737,22023,ATL,Atlanta Hawks,0022300521,2024-01-10,ATL vs. PHI,W,265,139,48,...,0.738,16,39,55,32,6,8,12,21,7.0
1610612737,22023,ATL,Atlanta Hawks,0022300499,2024-01-07,ATL @ ORL,L,265,110,42,...,0.586,8,42,50,21,9,10,12,23,-7.0
1610612737,22023,ATL,Atlanta Hawks,0022300480,2024-01-05,ATL @ IND,L,238,116,40,...,0.867,14,25,39,21,6,3,14,11,-34.0
1610612737,22023,ATL,Atlanta Hawks,0022300467,2024-01-03,ATL vs. OKC,W,240,141,48,...,0.939,15,34,49,30,8,5,11,21,3.0
1610612737,22023,ATL,Atlanta Hawks,0022300445,2023-12-31,ATL @ WAS,W,240,130,47,...,0.649,12,46,58,27,5,3,12,18,4.0
1610612737,22023,ATL,Atlanta Hawks,0022300431,2023-12-29,ATL vs. SAC,L,239,110,37,...,0.840,18,33,51,29,9,4,15,16,-7.0
1610612737,22023,ATL,Atlanta Hawks,0022300408,2023-12-26,ATL @ CHI,L,239,113,41,...,0.857,12,28,40,24,6,3,15,21,-5.0
1610612737,22023,ATL,Atlanta Hawks,0022300393,2023-12-23,ATL vs. MEM,L,239,119,45,...,0.800,13,28,41,28,8,5,10,22,-6.0
1610612737,22023,ATL,Atlanta Hawks,0022300384,2023-12-22,ATL @ MIA,L,240,113,42,...,0.714,12,31,43,29,9,2,13,23,-9.0
1610612737,22023,ATL,Atlanta Hawks,0022300371,2023-12-20,ATL @ HOU,W,240,134,47,...,0.821,12,32,44,31,4,3,9,18,7.0
1610612737,22023,ATL,Atlanta Hawks,0022300352,2023-12-18,ATL vs. DET,W,240,130,46,...,0.815,11,29,40,25,6,10,17,24,6.0
1610612737,22023,ATL,Atlanta Hawks,0022300336,2023-12-16,ATL @ CLE,L,239,119,41,...,0.880,6,28,34,21,5,4,11,21,-8.0
1610612737,22023,ATL,Atlanta Hawks,0022300330,2023-12-15,ATL @ TOR,W,239,125,52,...,0.833,16,39,55,34,4,4,12,19,21.0
1610612737,22023,ATL,Atlanta Hawks,0022300313,2023-12-13,ATL @ TOR,L,240,128,48,...,0.737,13,29,42,32,9,8,7,18,-7.0
1610612737,22023,ATL,Atlanta Hawks,0022300296,2023-12-11,ATL vs. DEN,L,240,122,44,...,0.944,13,22,35,25,9,2,10,21,-7.0
1610612737,22023,ATL,Atlanta Hawks,0022301218,2023-12-08,ATL @ PHI,L,241,114,41,...,0.905,23,32,55,20,3,4,13,23,-11.0
1610612737,22023,ATL,Atlanta Hawks,0022301209,2023-12-06,ATL vs. BKN,L,240,113,42,...,0.944,11,38,49,25,5,4,12,23,-1.0
1610612737,22023,ATL,Atlanta Hawks,0022300286,2023-12-02,ATL @ MIL,L,239,121,45,...,0.762,15,25,40,23,11,4,11,14,-11.0
1610612737,22023,ATL,Atlanta Hawks,0022300272,2023-11-30,ATL @ SAS,W,241,137,49,...,0.862,8,29,37,24,14,2,10,25,2.0
1610612737,22023,ATL,Atlanta Hawks,0022300055,2023-11-28,ATL @ CLE,L,239,105,35,...,0.917,14,30,44,21,9,3,10,16,-23.0
1610612737,22023,ATL,Atlanta Hawks,0022300246,2023-11-26,ATL @ BOS,L,240,103,36,...,0.632,11,32,43,15,5,4,15,17,-10.0
1610612737,22023,ATL,Atlanta Hawks,0022300241,2023-11-25,ATL @ WAS,W,239,136,52,...,0.700,17,32,49,29,13,2,9,15,28.0
1610612737,22023,ATL,Atlanta Hawks,0022300227,2023-11-22,ATL vs. BKN,W,264,147,51,...,0.931,22,36,58,24,10,8,14,18,2.0
1610612737,22023,ATL,Atlanta Hawks,0022300039,2023-11-21,ATL vs. IND,L,240,152,57,...,0.821,12,27,39,28,8,4,15,23,-5.0
1610612737,22023,ATL,Atlanta Hawks,0022300029,2023-11-17,ATL vs. PHI,L,239,116,40,...,0.800,14,25,39,24,8,4,13,20,-10.0
1610612737,22023,ATL,Atlanta Hawks,0022300193,2023-11-15,ATL vs. NYK,L,238,114,41,...,0.769,6,24,30,28,11,6,15,20,-2.0
1610612737,22023,ATL,Atlanta Hawks,0022300018,2023-11-14,ATL @ DET,W,240,126,45,...,0.923,10,31,41,28,9,7,14,19,6.0
1610612737,22023,ATL,Atlanta Hawks,0022300175,2023-11-11,ATL vs. MIA,L,240,109,38,...,0.833,15,33,48,23,6,6,21,19,-8.0
1610612737,22023,ATL,Atlanta Hawks,0022300172,2023-11-09,ATL @ ORL,W,240,120,41,...,0.767,8,28,36,22,13,7,17,25,1.0
1610612737,22023,ATL,Atlanta Hawks,0022300155,2023-11-06,ATL @ OKC,L,239,117,38,...,0.844,25,34,59,27,8,3,15,16,-9.0
1610612737,22023,ATL,Atlanta Hawks,0022300135,2023-11-04,ATL @ NOP,W,241,123,45,...,0.792,19,33,52,28,4,6,11,16,18.0
1610612737,22023,ATL,Atlanta Hawks,0022300117,2023-11-01,ATL vs. WAS,W,241,130,46,...,0.906,14,43,57,26,8,3,20,16,9.0
1610612737,22023,ATL,Atlanta Hawks,0022300104,2023-10-30,ATL vs. MIN,W,238,127,48,...,0.944,4,32,36,28,6,7,9,12,14.0
1610612737,22023,ATL,Atlanta Hawks,0022300097,2023-10-29,ATL @ MIL,W,241,127,47,...,0.818,13,33,46,32,15,2,17,17,17.0
1610612737,22023,ATL,Atlanta Hawks,0022300079,2023-10-27,ATL vs. NYK,L,240,120,42,...,0.800,9,35,44,28,7,6,14,20,-6.0
1610612737,22023,ATL,Atlanta Hawks,0022300063,2023-10-25,ATL @ CHA,L,240,110,39,...,0.818,12,30,42,24,12,1,12,19,-6.0
1610612738,22023,BOS,Boston Celtics,0022301186,2024-04-14,BOS vs. WAS,W,240,132,51,...,0.667,10,38,48,29,10,15,14,13,10.0
1610612738,22023,BOS,Boston Celtics,0022301173,2024-04-12,BOS vs. CHA,W,240,131,54,...,0.692,16,37,53,34,12,1,6,20,33.0
1610612738,22023,BOS,Boston Celtics,0022301167,2024-04-11,BOS vs. NYK,L,242,109,40,...,0.813,10,26,36,25,7,12,12,16,-9.0
1610612738,22023,BOS,Boston Celtics,0022301148,2024-04-09,BOS @ MIL,L,241,91,37,...,NaN,12,26,38,27,11,4,12,8,-13.0
1610612738,22023,BOS,Boston Celtics,0022301134,2024-04-07,BOS vs. POR,W,241,124,49,...,0.769,5,35,40,34,11,8,12,12,17.0
1610612738,22023,BOS,Boston Celtics,0022301118,2024-04-05,BOS vs. SAC,W,239,101,38,...,0.722,12,39,51,25,6,4,7,11,1.0
1610612738,22023,BOS,Boston Celtics,0022301105,2024-04-03,BOS vs. OKC,W,242,135,50,...,0.947,11,35,46,33,7,10,10,18,35.0
1610612738,22023,BOS,Boston Celtics,0022301087,2024-04-01,BOS @ CHA,W,239,118,43,...,0.813,11,40,51,28,3,3,10,15,14.0
1610612738,22023,BOS,Boston Celtics,0022301074,2024-03-30,BOS @ NOP,W,240,104,39,...,0.917,8,43,51,27,7,7,12,13,12.0
1610612738,22023,BOS,Boston Celtics,0022301060,2024-03-28,BOS @ ATL,L,267,122,45,...,0.857,9,34,43,28,7,6,12,15,-1.0
1610612738,22023,BOS,Boston Celtics,0022301034,2024-03-25,BOS @ ATL,L,241,118,47,...,0.684,12,26,38,21,7,8,7,16,-2.0
1610612738,22023,BOS,Boston Celtics,0022301023,2024-03-23,BOS @ CHI,W,240,124,44,...,0.882,12,29,41,28,5,3,12,9,11.0
1610612738,22023,BOS,Boston Celtics,0022301011,2024-03-22,BOS @ DET,W,241,129,47,...,0.704,8,27,35,31,9,5,7,15,27.0
1610612738,22023,BOS,Boston Celtics,0022300998,2024-03-20,BOS vs. MIL,W,238,122,40,...,0.828,11,26,37,25,6,5,9,18,3.0
1610612738,22023,BOS,Boston Celtics,0022300984,2024-03-18,BOS vs. DET,W,240,119,43,...,0.846,15,38,53,30,8,8,9,9,25.0
1610612738,22023,BOS,Boston Celtics,0022300980,2024-03-17,BOS @ WAS,W,241,130,43,...,0.833,12,31,43,30,9,6,14,17,26.0
1610612738,22023,BOS,Boston Celtics,0022300955,2024-03-14,BOS vs. PHX,W,240,127,47,...,0.727,6,27,33,31,12,5,8,13,15.0
1610612738,22023,BOS,Boston Celtics,0022300943,2024-03-12,BOS @ UTA,W,241,123,43,...,0.895,14,32,46,25,5,8,8,14,16.0
1610612738,22023,BOS,Boston Celtics,0022300938,2024-03-11,BOS @ POR,W,241,121,49,...,0.667,14,31,45,34,7,10,3,11,22.0
1610612738,22023,BOS,Boston Celtics,0022300920,2024-03-09,BOS @ PHX,W,240,117,46,...,0.769,13,30,43,29,7,4,12,12,10.0
1610612738,22023,BOS,Boston Celtics,0022300906,2024-03-07,BOS @ DEN,L,240,109,41,...,0.640,13,34,47,24,6,3,12,18,-6.0
1610612738,22023,BOS,Boston Celtics,0022300886,2024-03-05,BOS @ CLE,L,241,104,39,...,0.917,14,39,53,24,6,9,13,13,-1.0
1610612738,22023,BOS,Boston Celtics,0022300872,2024-03-03,BOS vs. GSW,W,240,140,53,...,0.818,7,44,51,35,10,5,7,19,52.0
1610612738,22023,BOS,Boston Celtics,0022300859,2024-03-01,BOS vs. DAL,W,240,138,52,...,1.000,9,38,47,33,4,8,9,15,28.0
1610612738,22023,BOS,Boston Celtics,0022300836,2024-02-27,BOS vs. PHI,W,240,117,39,...,0.919,9,47,56,21,7,9,14,16,18.0
1610612738,22023,BOS,Boston Celtics,0022300816,2024-02-24,BOS @ NYK,W,239,116,46,...,0.750,11,25,36,27,8,4,7,16,14.0
1610612738,22023,BOS,Boston Celtics,0022300797,2024-02-22,BOS @ CHI,W,240,129,45,...,0.762,5,31,36,27,10,11,13,16,17.0
1610612738,22023,BOS,Boston Celtics,0022300780,2024-02-14,BOS vs. BKN,W,240,136,52,...,0.833,10,41,51,32,6,5,8,13,50.0
1610612738,22023,BOS,Boston Celtics,0022300771,2024-02-13,BOS @ BKN,W,239,118,43,...,0.739,7,32,39,31,6,1,13,24,8.0
1610612738,22023,BOS,Boston Celtics,0022300759,2024-02-11,BOS @ MIA,W,240,110,41,...,0.706,6,36,42,27,1,9,9,13,4.0
1610612738,22023,BOS,Boston Celtics,0022300743,2024-02-09,BOS vs. WAS,W,240,133,48,...,0.929,9,40,49,25,9,5,13,17,4.0
1610612738,22023,BOS,Boston Celtics,0022300729,2024-02-07,BOS vs. ATL,W,240,125,49,...,0.909,6,39,45,33,6,9,14,16,8.0
1610612738,22023,BOS,Boston Celtics,0022300706,2024-02-04,BOS vs. MEM,W,242,131,48,...,0.889,17,40,57,30,12,4,10,13,40.0
1610612738,22023,BOS,Boston Celtics,0022300684,2024-02-01,BOS vs. LAL,L,240,105,41,...,1.000,14,40,54,30,4,12,15,19,-9.0
1610612738,22023,BOS,Boston Celtics,0022300670,2024-01-30,BOS vs. IND,W,240,129,47,...,0.818,7,33,40,25,6,9,10,16,5.0
1610612738,22023,BOS,Boston Celtics,0022300659,2024-01-29,BOS vs. NOP,W,240,118,43,...,0.750,6,34,40,27,7,5,11,15,6.0
1610612738,22023,BOS,Boston Celtics,0022300646,2024-01-27,BOS vs. LAC,L,240,96,36,...,0.875,18,34,52,21,2,9,11,13,-19.0
1610612738,22023,BOS,Boston Celtics,0022300630,2024-01-25,BOS @ MIA,W,239,143,51,...,0.950,6,41,47,36,4,5,11,10,33.0
1610612738,22023,BOS,Boston Celtics,0022300611,2024-01-22,BOS @ DAL,W,240,119,41,...,0.733,5,39,44,26,7,8,6,20,9.0
1610612738,22023,BOS,Boston Celtics,0022300603,2024-01-21,BOS @ HOU,W,240,116,43,...,0.722,16,39,55,31,10,12,16,17,9.0
1610612738,22023,BOS,Boston Celtics,0022300586,2024-01-19,BOS vs. DEN,L,240,100,38,...,0.714,12,26,38,21,5,2,2,17,-2.0
1610612738,22023,BOS,Boston Celtics,0022300571,2024-01-17,BOS vs. SAS,W,240,117,42,...,0.789,12,42,54,22,5,6,12,15,19.0
1610612738,22023,BOS,Boston Celtics,0022300563,2024-01-15,BOS @ TOR,W,240,105,33,...,0.920,5,48,53,20,3,7,12,16,9.0
1610612738,22023,BOS,Boston Celtics,0022300542,2024-01-13,BOS vs. HOU,W,239,145,51,...,0.760,10,40,50,26,7,8,11,21,32.0
1610612738,22023,BOS,Boston Celtics,0022300528,2024-01-11,BOS @ MIL,L,241,102,34,...,0.833,6,25,31,22,5,5,6,13,-33.0
1610612738,22023,BOS,Boston Celtics,0022300517,2024-01-10,BOS vs. MIN,W,263,127,39,...,0.968,7,39,46,21,5,4,8,19,7.0
1610612738,22023,BOS,Boston Celtics,0022300507,2024-01-08,BOS @ IND,L,240,131,47,...,0.690,13,29,42,26,3,8,15,20,-2.0
1610612738,22023,BOS,Boston Celtics,0022300493,2024-01-06,BOS @ IND,W,240,118,46,...,0.526,13,43,56,26,6,6,17,20,17.0
1610612738,22023,BOS,Boston Celtics,0022300479,2024-01-05,BOS vs. UTA,W,240,126,39,...,0.861,9,47,56,24,9,8,12,23,29.0
1610612738,22023,BOS,Boston Celtics,0022300462,2024-01-02,BOS @ OKC,L,241,123,42,...,0.828,17,30,47,33,7,10,14,15,-4.0
1610612738,22023,BOS,Boston Celtics,0022300448,2023-12-31,BOS @ SAS,W,240,134,51,...,0.773,13,44,57,29,6,7,10,12,33.0
1610612738,22023,BOS,Boston Celtics,0022300432,2023-12-29,BOS vs. TOR,W,239,120,43,...,0.850,13,39,52,29,3,6,16,17,2.0
1610612738,22023,BOS,Boston Celtics,0022300421,2023-12-28,BOS vs. DET,W,266,128,48,...,0.840,11,32,43,25,10,4,12,15,6.0
1610612738,22023,BOS,Boston Celtics,0022300403,2023-12-25,BOS @ LAL,W,240,126,46,...,0.750,11,33,44,31,8,7,8,17,11.0
1610612738,22023,BOS,Boston Celtics,0022300389,2023-12-23,BOS @ LAC,W,241,145,49,...,0.786,15,36,51,33,4,5,9,19,37.0
1610612738,22023,BOS,Boston Celtics,0022300373,2023-12-20,BOS @ SAC,W,239,144,51,...,0.833,14,36,50,35,6,10,9,17,25.0
1610612738,22023,BOS,Boston Celtics,0022300362,2023-12-19,BOS @ GSW,L,264,126,47,...,0.882,18,37,55,28,6,5,8,13,-6.0
1610612738,22023,BOS,Boston Celtics,0022300344,2023-12-17,BOS vs. ORL,W,239,114,45,...,0.875,10,45,55,18,4,10,14,19,17.0
1610612738,22023,BOS,Boston Celtics,0022300329,2023-12-15,BOS vs. ORL,W,240,128,48,...,0.700,9,25,34,31,14,7,10,22,17.0
1610612738,22023,BOS,Boston Celtics,0022300319,2023-12-14,BOS vs. CLE,W,240,116,43,...,0.850,13,31,44,22,7,8,13,15,9.0
1610612738,22023,BOS,Boston Celtics,0022300305,2023-12-12,BOS vs. CLE,W,241,120,38,...,1.000,12,33,45,23,9,9,13,13,7.0
1610612738,22023,BOS,Boston Celtics,0022301227,2023-12-08,BOS vs. NYK,W,240,133,48,...,0.857,8,26,34,24,8,5,7,19,10.0
1610612738,22023,BOS,Boston Celtics,0022301202,2023-12-04,BOS @ IND,L,239,112,46,...,0.667,13,43,56,27,5,9,17,19,-10.0
1610612738,22023,BOS,Boston Celtics,0022300275,2023-12-01,BOS vs. PHI,W,239,125,39,...,0.861,10,36,46,25,10,8,20,18,6.0
1610612738,22023,BOS,Boston Celtics,0022300053,2023-11-28,BOS vs. CHI,W,241,124,47,...,0.750,11,41,52,36,6,9,16,18,27.0
1610612738,22023,BOS,Boston Celtics,0022300246,2023-11-26,BOS vs. ATL,W,239,113,42,...,0.800,18,40,58,24,9,3,12,19,10.0
1610612738,22023,BOS,Boston Celtics,0022300043,2023-11-24,BOS @ ORL,L,240,96,31,...,0.730,4,27,31,17,10,4,14,18,-17.0
1610612738,22023,BOS,Boston Celtics,0022300228,2023-11-22,BOS vs. MIL,W,240,119,44,...,0.824,4,39,43,27,3,5,15,15,3.0
1610612738,22023,BOS,Boston Celtics,0022300217,2023-11-20,BOS @ CHA,L,264,118,42,...,0.643,11,37,48,19,6,8,13,15,-3.0
1610612738,22023,BOS,Boston Celtics,0022300213,2023-11-19,BOS @ MEM,W,241,102,35,...,0.800,9,36,45,20,6,10,17,19,2.0
1610612738,22023,BOS,Boston Celtics,0022300031,2023-11-17,BOS @ TOR,W,240,108,42,...,0.889,8,36,44,29,5,4,10,13,3.0
1610612738,22023,BOS,Boston Celtics,0022300194,2023-11-15,BOS @ PHI,W,239,117,42,...,0.789,12,33,45,23,7,8,9,15,10.0
1610612738,22023,BOS,Boston Celtics,0022300188,2023-11-13,BOS vs. NYK,W,238,114,40,...,0.938,8,29,37,27,3,3,11,22,16.0
1610612738,22023,BOS,Boston Celtics,0022300174,2023-11-11,BOS vs. TOR,W,242,117,47,...,0.615,5,41,46,30,1,4,12,14,23.0
1610612738,22023,BOS,Boston Celtics,0022300010,2023-11-10,BOS vs. BKN,W,241,121,41,...,0.714,17,35,52,29,5,3,7,13,14.0
1610612738,22023,BOS,Boston Celtics,0022300159,2023-11-08,BOS @ PHI,L,241,103,36,...,0.842,9,34,43,28,8,6,12,13,-3.0
1610612738,22023,BOS,Boston Celtics,0022300154,2023-11-06,BOS @ MIN,L,265,109,36,...,0.765,11,34,45,20,13,2,16,26,-5.0
1610612738,22023,BOS,Boston Celtics,0022300136,2023-11-04,BOS @ BKN,W,240,124,43,...,0.852,10,40,50,22,4,6,11,17,10.0
1610612738,22023,BOS,Boston Celtics,0022300118,2023-11-01,BOS vs. IND,W,239,155,54,...,0.964,11,46,57,27,5,2,11,19,51.0
1610612738,22023,BOS,Boston Celtics,0022300103,2023-10-30,BOS @ WAS,W,243,126,51,...,0.714,15,36,51,31,11,6,17,21,19.0
1610612738,22023,BOS,Boston Celtics,0022300080,2023-10-27,BOS vs. MIA,W,239,119,45,...,0.684,16,39,55,20,7,6,15,19,8.0
1610612738,22023,BOS,Boston Celtics,0022300065,2023-10-25,BOS @ NYK,W,241,108,37,...,0.846,7,39,46,18,6,11,13,22,4.0
1610612739,22023,CLE,Cleveland Cavaliers,0022301187,2024-04-14,CLE vs. CHA,L,241,110,44,...,0.667,12,31,43,30,4,1,14,8,-10.0
1610612739,22023,CLE,Cleveland Cavaliers,0022301174,2024-04-12,CLE vs. IND,W,241,129,50,...,0.696,11,30,41,28,9,2,9,14,9.0
1610612739,22023,CLE,Cleveland Cavaliers,0022301158,2024-04-10,CLE vs. MEM,W,243,110,37,...,0.724,12,35,47,27,11,10,13,15,12.0

In [ ]:
#this is likely the endpoint we will use:
from nba_api.stats.endpoints import leaguegamefinder
from sqlalchemy import create_engine
from requests.exceptions import ReadTimeout
import pandas as pd
import random
import time 
import json

#create our engine for pushing to sql database
from dotenv import load_dotenv
import os

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

engine = create_engine(DATABASE_URL)

#define seasons to gather data for 
seasons = ['2022-23', '2023-24', '2024-25']

for season in seasons:
    try:
        # Get all games for a season
        game_finder = leaguegamefinder.LeagueGameFinder(
            season_nullable=season,  # Format: YYYY-YY
            league_id_nullable='00',    # 00 is NBA
            season_type_nullable='Regular Season'  # or 'Playoffs'
        )
        
        # Convert to DataFrame
        games_df = game_finder.get_data_frames()[0]
        
        #make team ID the index, and sort the dataframe based on ID and gameDate
        games_df = games_df.set_index('TEAM_ID')
        games_df_sorted = games_df.sort_values(['TEAM_ID', 'GAME_DATE'], ascending=[True, False])
    
        #once we've created the dataframe, we want to push that to a SQL database
        filename = f"{season}_historic_game_data"
        games_df_sorted.to_sql(filename, engine, if_exists='replace', index=False)
        print(f"Created and stored dataframe for {season} season")
        print()
        time.sleep(round(random.uniform(3, 6), 1))

    #handle timeout/api rejection errors
    except (ReadTimeout, json.decoder.JSONDecodeError) as e:
        print(f"Error for {season}: {e} - retrying after 60 seconds")
        time.sleep(60)
        continue

print("Finished data gathering for specified seasons")

Created and stored dataframe for 2022-23 season

Created and stored dataframe for 2023-24 season

Created and stored dataframe for 2024-25 season

Finished data gathering for specified seasons

In [51]:
#set display options ot max size 
pd.set_option('display.max_rows', 2460)
pd.set_option('display.max_rows', 55)

games_df_sorted

,SEASON_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
TEAM_ID,,,,,,,,,,,,,,,,,,,,,
1610612737,22024,ATL,Atlanta Hawks,0022400639,2025-01-25,ATL vs. TOR,L,238,94,33,...,0.680,8,35,43,28,14,5,22,20,-23.0
1610612737,22024,ATL,Atlanta Hawks,0022400623,2025-01-23,ATL vs. TOR,L,240,119,42,...,0.733,9,27,36,30,11,2,14,21,-3.0
1610612737,22024,ATL,Atlanta Hawks,0022400612,2025-01-22,ATL vs. DET,L,241,104,39,...,0.769,15,32,47,25,14,3,13,14,-10.0
1610612737,22024,ATL,Atlanta Hawks,0022400602,2025-01-20,ATL @ NYK,L,239,110,40,...,0.773,16,25,41,23,10,6,23,21,-9.0
1610612737,22024,ATL,Atlanta Hawks,0022400587,2025-01-18,ATL @ BOS,W,265,119,44,...,0.786,13,42,55,27,9,10,17,17,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1610612766,22024,CHA,Charlotte Hornets,0022400132,2024-11-01,CHA vs. BOS,L,241,109,42,...,0.500,12,30,42,20,5,5,14,26,-15.0
1610612766,22024,CHA,Charlotte Hornets,0022400117,2024-10-30,CHA vs. TOR,W,239,138,49,...,0.800,14,24,38,31,9,8,15,24,5.0
1610612766,22024,CHA,Charlotte Hornets,0022400088,2024-10-26,CHA vs. MIA,L,241,106,39,...,0.714,15,31,46,20,6,5,17,24,-8.0
1610612766,22024,CHA,Charlotte Hornets,0022400079,2024-10-25,CHA @ ATL,L,241,120,37,...,0.806,22,31,53,22,7,4,17,28,-5.0
1610612766,22024,CHA,Charlotte Hornets,0022400068,2024-10-23,CHA @ HOU,W,241,110,38,...,0.792,15,41,56,20,6,10,16,21,5.0